const pizzaList = [
  {
    id: 1,
    image: process.env.PUBLIC_URL + '/images/image1.png',
    name: 'Margherita Pizza',
    price: 8.99,
    oldPrice: 12.99,
    description: 'Sự kết hợp hoàn hảo giữa phô mai Mozzarella và sốt cà chua truyền thống.',
    tags: ['Sale', 'New'],
  },
  {
    id: 2,
    image: process.env.PUBLIC_URL + '/images/image2.png',
    name: 'Mushroom Pizza',
    price: 9.50,
    oldPrice: null,
    description: 'Nấm tươi cao cấp kết hợp cùng sốt kem trắng béo ngậy.',
    tags: null,
  },
  {
    id: 3,
    image: process.env.PUBLIC_URL + '/images/image3.png',
    name: 'Hawaiian Pizza',
    price: 10.99,
    oldPrice: 15.00,
    description: 'Hương vị nhiệt đới với sự kết hợp của dứa tươi và thịt nguội.',
    tags: ['Sale'],
  },
  {
    id: 4,
    image: process.env.PUBLIC_URL + '/images/image4.png',
    name: 'Pesto Chicken',
    price: 11.99,
    oldPrice: null,
    description: 'Gà nướng thơm lừng hòa quyện cùng sốt Pesto đặc trưng từ húng tây.',
    tags: ['New'],
  },
  {
    id: 5,
    image: process.env.PUBLIC_URL + '/images/image5.png',
    name: 'Pepperoni Feast',
    price: 12.50,
    oldPrice: 14.99,
    description: 'Xúc xích Pepperoni đậm đà phủ kín mặt bánh giòn rụm.',
    tags: ['Sale'],
  },
  {
    id: 6,
    image: process.env.PUBLIC_URL + '/images/image6.png',
    name: 'Veggie Supreme',
    price: 9.99,
    oldPrice: null,
    description: 'Thế giới rau củ tươi ngon: ớt chuông, hành tây, nấm và oliu.',
    tags: null,
  },
  {
    id: 7,
    image: process.env.PUBLIC_URL + '/images/image7.png',
    name: 'BBQ Beef Pizza',
    price: 13.99,
    oldPrice: 16.50,
    description: 'Thịt bò băm nướng sốt BBQ đậm đà, khó cưỡng.',
    tags: ['New', 'Sale'],
  },
  {
    id: 8,
    image: process.env.PUBLIC_URL + '/images/image8.png',
    name: 'Seafood Deluxe',
    price: 15.99,
    oldPrice: null,
    description: 'Hải sản cao cấp: tôm, mực tươi và sốt phô mai đặc biệt.',
    tags: ['New'],
  },
  {
    id: 9,
    image: process.env.PUBLIC_URL + '/images/image9.png',
    name: 'Four Cheese',
    price: 11.00,
    oldPrice: 13.00,
    description: 'Bữa tiệc phô mai với 4 loại phô mai trứ danh thế giới.',
    tags: ['Sale'],
  },
  {
    id: 10,
    image: process.env.PUBLIC_URL + '/images/image10.png',
    name: 'Spicy Sausage',
    price: 10.50,
    oldPrice: null,
    description: 'Xúc xích cay nồng dành cho những tín đồ yêu thích vị giác mạnh.',
    tags: null,
  }
];

export default pizzaList;
